# .cnb.yml
$:
  vscode:
    - docker:
        image: docker.cnb.cool/zecrimp/zet-dev-env
      services:
        - vscode
        - docker
      stages:
        - name: install
          script: pnpm i
# .cnb.yml
main:
  push:
    - imports:
        - https://cnb.cool/Zecrimp/secret/-/blob/main/.github.yml
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/my-name-is-not-available/blog-preference.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            git_user: ${GIT_USERNAME}
            git_email: ${GIT_EMAIL}